name: One-Push

on:
  workflow_dispatch:

jobs:
  Config:
    runs-on: ubuntu-latest

    steps:
      - name: Login To Aliyun
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PWD }}
          
      - name: docker pull and tag and push Image
        run: |
          docker pull joyqi/typecho:nightly-php8.2-fpm
          docker tag joyqi/typecho:nightly-php8.2-fpm registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/typecho:nightly-php8.2-fpm
          docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/typecho:nightly-php8.2-fpm
          docker image rm joyqi/typecho:nightly-php8.2-fpm registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/typecho:nightly-php8.2-fpm
